[package]
name = "mud_lang"
version = "0.1.0"
authors = ["Wil Hunt <huntwj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.0.1"   
nom_locate = "1.0.0"
